language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
env: 
    global:
        secure: "kINzXN60o68vnvkhWNaaIwsPhUUAwjuUjkq9f+YuP5AYAJIyOdXtnHYpZnMxU7tSuz8nczAXRHBj0EW2M7Q4EIpEMQiPtZ9ejxzqHm4A1zMTSftvte7tK4Gs3iWyI5Sexi3Guy3Q20DtBr1gPDyrkS3G528R/vly5DFp6XDcik0="
